### PR TITLE
DSA Sorting Algorithms

### PR DESCRIPTION
**Pull request by tandrimasingha**
Sir, I did three sorting algorithms.
Please do check the algorithms and do merge them.

### CODE REVIEW

**Comment by Jaideep25-tech** [comment]
thats great awesome work

**Comment by Jaideep25-tech** [comment]
can you pls again create the pr with these pr inside algorithms folder there is sorting named folder and there are different sorting folders

**Comment by tandrimasingha** [comment]
How to do this please tell me

**Comment by Jaideep25-tech** [comment]
I am removing the pr go to that directory upload the files there and then again create the pr!

**Pull request merged**
